apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - github.com/prometheus-operator/prometheus-operator?ref=v0.67.0/manifests

patchesStrategicMerge:
  - single-node-etcd.yaml
  - no-taints.yaml
  - replica-patches.yaml

patchesJson6902:
  - target:
      group: monitoring.coreos.com
      version: v1
      kind: Prometheus
      name: prometheus-kube-prometheus-prometheus
    path: prometheus-patch.json

configMapGenerator:
  - name: grafana-config
    files:
      - grafana-datasources.yaml=grafana.yaml
    options:
      disableNameSuffixHash: true